export type VehicleStatus = 'vente' | 'vendu' | 'preparation'

export interface Vehicle {
  id: string
  slug: string
  statut: VehicleStatus
  marque: string
  modele: string
  version: string
  annee: number
  km: number
  prix: number | null
  couleur: string
  couleurInterieure: string
  carburant: string
  boite: string
  puissance: number
  portes: number
  places: number
  normeEuro: string
  options: string[]
  description: string
  photos: string[]
  video360: string | null
  prixMarcheLbc: number | null
  prixMarcheCentrale: number | null
  nbProprietaires: number
  ctOk: boolean
  carnetSuivi: boolean
  featured: boolean
}

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'porsche-911-carrera-2022-18000km',
    statut: 'vente',
    marque: 'Porsche',
    modele: '911',
    version: 'Carrera 4S',
    annee: 2022,
    km: 18000,
    prix: 129900,
    couleur: 'Noir Jet',
    couleurInterieure: 'Cuir Bordeaux',
    carburant: 'Essence',
    boite: 'PDK',
    puissance: 450,
    portes: 2,
    places: 4,
    normeEuro: 'Euro 6d',
    options: ['Sport Chrono', 'Toit ouvrant panoramique', 'Caméra 360°', 'Bose Audio', 'Phares LED Matrix', 'Sièges chauffants', 'Echappement Sport'],
    description: 'Porsche 911 Carrera 4S en parfait état, première main. Historique complet Porsche Center. Finition impeccable, aucun défaut.',
    photos: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=80',
      'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=1200&q=80',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: 134500,
    prixMarcheCentrale: 136000,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: true,
  },
  {
    id: '2',
    slug: 'lamborghini-huracan-2020-22000km',
    statut: 'vente',
    marque: 'Lamborghini',
    modele: 'Huracán',
    version: 'EVO RWD',
    annee: 2020,
    km: 22000,
    prix: 219000,
    couleur: 'Giallo Belenus',
    couleurInterieure: 'Alcantara Noir',
    carburant: 'Essence',
    boite: 'LDF',
    puissance: 610,
    portes: 2,
    places: 2,
    normeEuro: 'Euro 6d',
    options: ['Lift System', 'Carbon Ceramic Brakes', 'Sensonum Audio', 'Targa Mode', 'Ad Personam'],
    description: 'Huracán EVO dans la légendaire teinte Giallo. Entretien Lamborghini Paris, état concours.',
    photos: [
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: 229000,
    prixMarcheCentrale: 225000,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: true,
  },
  {
    id: '3',
    slug: 'ferrari-f8-tributo-2021-9000km',
    statut: 'vente',
    marque: 'Ferrari',
    modele: 'F8 Tributo',
    version: 'Spider',
    annee: 2021,
    km: 9000,
    prix: 299000,
    couleur: 'Rosso Corsa',
    couleurInterieure: 'Cuir Beige',
    carburant: 'Essence',
    boite: 'F1 DCT',
    puissance: 720,
    portes: 2,
    places: 2,
    normeEuro: 'Euro 6d',
    options: ['Lift', 'Carbon Package', 'Racing Seats', 'Hi-Fi Premium', 'Telemetria'],
    description: 'Ferrari F8 Spider, la plus belle des cabriolets modernes. Livraison Ferrari Côte d\'Azur, traçabilité parfaite.',
    photos: [
      'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: 315000,
    prixMarcheCentrale: 310000,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: true,
  },
  {
    id: '4',
    slug: 'mclaren-720s-2019-31000km',
    statut: 'vente',
    marque: 'McLaren',
    modele: '720S',
    version: 'Performance',
    annee: 2019,
    km: 31000,
    prix: 189000,
    couleur: 'Papaya Spark',
    couleurInterieure: 'Alcantara Noir/Orange',
    carburant: 'Essence',
    boite: 'SSG',
    puissance: 720,
    portes: 2,
    places: 2,
    normeEuro: 'Euro 6c',
    options: ['Track Pack', 'MSO Floor Mats', 'Electrochromic Roof', 'Bowers & Wilkins'],
    description: 'McLaren 720S Performance en Papaya Spark. La supercar britannique dans sa meilleure expression.',
    photos: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: 198000,
    prixMarcheCentrale: 195000,
    nbProprietaires: 2,
    ctOk: true,
    carnetSuivi: true,
    featured: true,
  },
  {
    id: '5',
    slug: 'bmw-m4-competition-2023-5000km',
    statut: 'vente',
    marque: 'BMW',
    modele: 'M4',
    version: 'Competition xDrive',
    annee: 2023,
    km: 5000,
    prix: 109900,
    couleur: 'Isle of Man Green',
    couleurInterieure: 'Cuir Noir Mérinos',
    carburant: 'Essence',
    boite: 'M Steptronic',
    puissance: 510,
    portes: 2,
    places: 4,
    normeEuro: 'Euro 6d',
    options: ['Pack Carbon', 'Sièges M Racing', 'HUD', 'Harman Kardon', 'Laser Light'],
    description: 'BMW M4 Competition xDrive quasi neuve. La GT la plus polyvalente du segment.',
    photos: [
      'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&q=80',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: 115000,
    prixMarcheCentrale: 113000,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
  {
    id: '6',
    slug: 'aston-martin-db11-2020-28000km',
    statut: 'vente',
    marque: 'Aston Martin',
    modele: 'DB11',
    version: 'V8 Volante',
    annee: 2020,
    km: 28000,
    prix: 169000,
    couleur: 'Magnetic Silver',
    couleurInterieure: 'Cuir Tan',
    carburant: 'Essence',
    boite: 'ZF 8 rapports',
    puissance: 510,
    portes: 2,
    places: 4,
    normeEuro: 'Euro 6d',
    options: ['Bang & Olufsen', 'Touring Pack', 'Premium Audio', 'Parking Sensors'],
    description: 'Aston Martin DB11 Volante, le grand tourisme par excellence. Élégance britannique et performance V8.',
    photos: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: 177000,
    prixMarcheCentrale: 174000,
    nbProprietaires: 2,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
  // VENDUS
  {
    id: '7',
    slug: 'bentley-continental-gt-2021-vendu',
    statut: 'vendu',
    marque: 'Bentley',
    modele: 'Continental GT',
    version: 'V8',
    annee: 2021,
    km: 19000,
    prix: 249000,
    couleur: 'Verdant',
    couleurInterieure: 'Cuir Créme/Chocolat',
    carburant: 'Essence',
    boite: 'DCT 8',
    puissance: 550,
    portes: 2,
    places: 4,
    normeEuro: 'Euro 6d',
    options: ['Naim Audio', 'Touring Spec', 'City Spec', 'Rotating Display'],
    description: 'Bentley Continental GT V8, vendu à un client heureux.',
    photos: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: null,
    prixMarcheCentrale: null,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
  {
    id: '8',
    slug: 'rolls-royce-ghost-2020-vendu',
    statut: 'vendu',
    marque: 'Rolls-Royce',
    modele: 'Ghost',
    version: 'Extended',
    annee: 2020,
    km: 45000,
    prix: 289000,
    couleur: 'Andalucian White',
    couleurInterieure: 'Cuir Seashell',
    carburant: 'Essence',
    boite: 'ZF Automatique',
    puissance: 571,
    portes: 4,
    places: 5,
    normeEuro: 'Euro 6d',
    options: ['Starlight Headliner', 'Bespoke Audio', 'Lounge Seats'],
    description: 'Rolls-Royce Ghost Extended, l\'ultime limousine. Vendu.',
    photos: [
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: null,
    prixMarcheCentrale: null,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
  {
    id: '9',
    slug: 'ferrari-sf90-2022-vendu',
    statut: 'vendu',
    marque: 'Ferrari',
    modele: 'SF90',
    version: 'Stradale',
    annee: 2022,
    km: 3200,
    prix: 549000,
    couleur: 'Bianco Avus',
    couleurInterieure: 'Alcantara Nero',
    carburant: 'Hybride',
    boite: 'F1 DCT',
    puissance: 1000,
    portes: 2,
    places: 2,
    normeEuro: 'Euro 6d',
    options: ['Assetto Fiorano', 'Carbon Pack', 'JBL Audio'],
    description: 'Ferrari SF90 Stradale, le sommet technologique de Maranello. Vendu.',
    photos: [
      'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: null,
    prixMarcheCentrale: null,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
  // EN PRÉPARATION
  {
    id: '10',
    slug: 'bugatti-chiron-2019-preparation',
    statut: 'preparation',
    marque: 'Bugatti',
    modele: 'Chiron',
    version: 'Sport',
    annee: 2019,
    km: 8000,
    prix: null,
    couleur: 'French Racing Blue',
    couleurInterieure: 'Cuir Bleu/Noir',
    carburant: 'Essence',
    boite: 'DSG 7',
    puissance: 1500,
    portes: 2,
    places: 2,
    normeEuro: 'Euro 6c',
    options: ['Sky View', 'Sport Exhaust', 'Visible Carbon'],
    description: 'Bugatti Chiron Sport en cours de préparation. Disponible sous 3 semaines.',
    photos: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: null,
    prixMarcheCentrale: null,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
  {
    id: '11',
    slug: 'koenigsegg-agera-2018-preparation',
    statut: 'preparation',
    marque: 'Koenigsegg',
    modele: 'Agera',
    version: 'RS',
    annee: 2018,
    km: 12000,
    prix: null,
    couleur: 'Silver Carbon',
    couleurInterieure: 'Alcantara Gris',
    carburant: 'Essence',
    boite: 'Paddle Shift',
    puissance: 1360,
    portes: 2,
    places: 2,
    normeEuro: 'Euro 6',
    options: ['Triplex Suspension', 'KERS', 'Carbon Ceramic'],
    description: 'Koenigsegg Agera RS, hypercar suédoise. En préparation.',
    photos: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80',
    ],
    video360: null,
    prixMarcheLbc: null,
    prixMarcheCentrale: null,
    nbProprietaires: 1,
    ctOk: true,
    carnetSuivi: true,
    featured: false,
  },
]

export function getVehiclesByStatus(status: VehicleStatus) {
  return vehicles.filter((v) => v.statut === status)
}

export function getVehicleBySlug(slug: string) {
  return vehicles.find((v) => v.slug === slug) ?? null
}

export function getFeaturedVehicles() {
  return vehicles.filter((v) => v.featured && v.statut === 'vente')
}

export function formatPrice(price: number | null): string {
  if (!price) return 'Sur demande'
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(price)
}

export function formatKm(km: number): string {
  return new Intl.NumberFormat('fr-FR').format(km) + ' km'
}
